name: action personalizada get cache y dependencias
description: obtener cache via npm y dependencias
inputs:
  guarda_cache: 
    description: 'valor para estrablecer las dependencias'
    required: false
    default: true
outputs:
  mi_cache:
    description: 'valor para describir si se uso la cache'
    value: ${{steps.instalacion.outputs.valor_regreso_cache}}

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.guarda_cache=='true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      id: instalacion
      if: steps.cache.outputs.cache-hit != 'true' || inputs.guarda_cache!='true'
      run: |
        npm ci
        echo "valor_regreso_cache= '${{inputs.guarda_cache}}'">> $GITHUB_OUTPUT
      shell: bash
  
